<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Denizs-MBP-2.fios-router.home" failures="1" tests="3" name="Command line test" time="18.524" errors="0" timestamp="2022-05-21T17:07:52 EDT">
  <testcase classname="scripts._01_AppleTest" name="X" time="0.002">
    <failure type="java.lang.AssertionError" message="Failure on purpose">
      <![CDATA[java.lang.AssertionError: Failure on purpose
at scripts._01_AppleTest.X(_01_AppleTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- X -->
  <testcase classname="scripts._01_AppleTest" name="testAppleTitle" time="2.38"/>
  <testcase classname="scripts._01_AppleTest" name="testAppleURL" time="2.342"/>
</testsuite> <!-- Command line test -->
